### ISSUE TITLE
Numpy issue when running on lxplus

### ISSUE THREAD

**Issue by jennetd** [cms-analysis/CombineHarvester#265]
Hi there,

I have set up the CombineTool code on lxplus according to the instructions in the README for this repo (CMSSW_10_2_13 and Combine tag v8.2.0), but I see an error related to the numpy installation. Is this a known problem? And is there a workaround?

Thanks,
Jennet

Here is an example command and the accompanying error:

[jdickins@lxplus795 2016-prefit]$ combineTool.py -M Impacts -d $modelfile -m 125 --robustFit 1 --doInitialFit -t -1 --setParameters rggF=1,rVBF=1,rZbb=1
Traceback (most recent call last):
  File "/afs/cern.ch/work/j/jdickins/hbb-prod-modes/test/CMSSW_10_2_13/bin/slc7_amd64_gcc700/combineTool.py", line 8, in <module>
    from CombineHarvester.CombineTools.combine.ImpactsFromScans import ImpactsFromScans
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/afs/cern.ch/work/j/jdickins/hbb-prod-modes/test/CMSSW_10_2_13/python/CombineHarvester/CombineTools/combine/ImpactsFromScans.py", line 15, in <module>
    from numpy import matrix
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.25/InstallArea/x86_64-slc6-gcc62-opt/lib/python2.7/site-packages/numpy-1.13.3-py2.7-linux-x86_64.egg/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.25/InstallArea/x86_64-slc6-gcc62-opt/lib/python2.7/site-packages/numpy-1.13.3-py2.7-linux-x86_64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.25/InstallArea/x86_64-slc6-gcc62-opt/lib/python2.7/site-packages/numpy-1.13.3-py2.7-linux-x86_64.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.25/InstallArea/x86_64-slc6-gcc62-opt/lib/python2.7/site-packages/numpy-1.13.3-py2.7-linux-x86_64.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc700/lcg/root/6.12.07-gnimlf5/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/cvmfs/atlas.cern.ch/repo/sw/software/21.2/AnalysisBaseExternals/21.2.25/InstallArea/x86_64-slc6-gcc62-opt/lib/python2.7/site-packages/numpy-1.13.3-py2.7-linux-x86_64.egg/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libptf77blas.so.3: cannot open shared object file: No such file or directory

**Comment by adewit** [comment]
Hi Jennet,

it looks like you don’t have a clean CMSSW environment, I see some lines from the error message pointing to ATLAS analysis code which might be interfering. Can you try without the paths pointing to the atlas code? (I don’t know of they are there because you initialized an atlas environment earlier or if these are set in your bashrc)

**Comment by jennetd** [comment]
Hi @adewit, thanks very much - this was in fact the issue! Not sure how an ancient ATLAS numpy installation stuck around as my default for so long, but all runs beautifully now. - Jennet
